#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  setup_must_be="developer/tool/setup"
  if [ "$SETUP" != "$setup_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $setup_must_be environment"
    exit 1
  fi

set -e
set -x

  cd "$REPO_HOME"/developer || exit 1
  # /bin/make -f tool/makefile $@

  scratchpad clear
  make
  release clean
  release write

set +x
echo "$(script_fn) done."
