#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

setup_must_be="developer/tool/setup"
if [ "$SETUP" != "$setup_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $setup_must_be environment"
  exit 1
fi

set -euo pipefail # RT-style shell safety
set -x

  # Command is first, Namespace is second
  CMD="${1:-usage}"
  NAMESPACE_ARG="${2:-}"

  cd "$REPO_HOME/developer" || exit 1

  # Pass both to the orchestrator
  NAMESPACE="$NAMESPACE_ARG" /bin/make -f tool/makefile "$CMD"

set +x
echo "$(script_fn) done."

